import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { Roboto } from 'next/font/google'
import FontSizeControl from "./components/FontSizeControl";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin', 'vietnamese'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className={roboto.className}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Header />
          {children}
          <FontSizeControl />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
